spring:
  profiles:
    active: dev

  main:
    banner-mode: "off"

  mvc:
    view:
      prefix: /static/
    servlet:
      load-on-startup: 1
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false

server:
  port: 8000
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
    include-exception: false
  servlet:
    context-path: /
  compression:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

---
# Configuration for Development Environment

spring:
  profiles:
    - dev
    - development

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka/"

lti-app:
  exam-taking-url-template: "https://cep.bellotapps.com/take-exam?exam-id=${exam-id}&access-token=${access-token}&refresh-token=${refresh-token}&token-id=${token-id}"

---
# Configuration for Staging Environment

spring:
  profiles:
    - staging

---
# Configuration for Production Environment

spring:
  profiles:
    - prod
    - production
